### ISSUE TITLE
Uploading images returns blank screen

### ISSUE THREAD

**Issue by egge-admin** [egge-space/egge-app-public#8]
While attempting to upload a profile photo, some users have seen a blank screen with no option to select a photo. 
Users reporting the issue are on iPhone 11/11+ and iOS 14.3.

**Comment by egge-admin** [comment]
Image of the screen attached
![image](https://user-images.githubusercontent.com/78390393/106535662-bbad5a80-64c4-11eb-9470-8374156724a7.png)

**Comment by egge-space** [comment]
This is related to #15 , this should be resolved now.
